version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      nest:
        patterns: ["@nestjs/*"]
      prisma:
        patterns: ["prisma", "@prisma/*"]
      types:
        patterns: ["@types/*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/apps/api"
    schedule:
      interval: "monthly"
